name: Swift

on:
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro Max']

    steps:
    - uses: actions/checkout@v1
    - name: Build Library
    run: |
        xcodebuild clean build -project PNPForm.xcodeproj -scheme PNPForm -destination "${destination}"
    - name: Build Sample App
    run: |
        xcodebuild clean build -project PNPForm.xcodeproj -scheme PNPFormSampleApp -destination "${destination}"
    - name: Run Tests
      run: |
          xcodebuild -project PNPForm.xcodeproj -scheme PNPFormTests -destination "${destination}" test
      env:
         destination: ${{ matrix.destination }}
